version: "3.4"
services:
  rethinkdb:
    image: "rethinkdb:2.3"
    container_name: rethinkdb
    ports:
      - "28015"
    volumes:
      - /data:/data
  redis:
    image: "redis:5.0-rc"
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: always
    expose:
      - 6379
  elasticsearch:
    container_name: search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"

volumes:
  esdata: